name = "Mainroad-safire"
license = "GPLv2"
licenselink = "https://github.com/vimux/mainroad/blob/master/LICENSE.md"
description = "Mainroad-safire is a responsive, clean and content-focused Hugo theme with SAFIRE branding."
homepage = "https://safire.ac.za/"
tags = ["blog", "responsive", "light", "multilingual", "customizable", "widgets", "safire"]
features = ["blog", "responsive", "multilingual", "widgets", "rss", "google analytics"]
min_version = "0.54.0"

[author]
  name = "SAFIRE"
  homepage = "https://safire.ac.za/"

# If porting an existing theme
[original]
  name = "Mainroad"
  homepage = "https://github.com/vimux/mainroad/"
  repo = "https://github.com/vimux/mainroad"
