---
name: github pages

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Create example data
        run: wget -O data/safire.json https://safire.ac.za/.safire-website-helpers/list-participants-hugo.php

      - name: Build
        run: hugo --minify --buildDrafts --baseURL https://tenet-ac-za.github.io/safire.ac.za-website/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
